name: progress

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}

      - name: Setup
        id: day-of-week
        run: echo "::set-output name=value::$(date +"%w")"

      - name: Echo
        run: echo ${{ steps.day-of-week.outputs.value }}
